on: [push, pull_request]
name: CI
jobs:
  build:
    name: "Build on Racket '${{ matrix.racket-version }}' (${{ matrix.racket-variant }})"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        racket-version: ["stable", "current"]
        racket-variant: ["BC", "CS"]
    steps:
      - uses: actions/checkout@v4
      - uses: Bogdanp/setup-racket@v1.11
        with:
          architecture: x64
          distribution: full
          variant: ${{ matrix.racket-variant }}
          version: ${{ matrix.racket-version }}
      - name: Installing typed-racket-stream and its dependencies
        run: raco pkg install --auto --name typed-racket-stream
      - name: Checking dependencies
        run: raco setup --check-pkg-deps --unused-pkg-deps typed
      - name: Testing typed-racket-stream
        run: raco test -p typed-racket-stream
